# arxiv/fulltext-agent

FROM arxiv/fulltext-api:latest

VOLUME /checkpoint

ENV KINESIS_STREAM "PDFIsAvailable"
ENV KINESIS_SHARD_ID "0"
ENV KINESIS_CHECKPOINT_VOLUME "/checkpoint"
ENV KINESIS_START_TYPE "AT_TIMESTAMP"

# Add the application itself last, for faster builds on minor revisions.
ADD bin/start_agent.py /opt/arxiv/
ADD bin/start_agent.sh /opt/arxiv/

ENTRYPOINT ["/opt/arxiv/start_agent.sh"]
