# arxiv/fulltext-worker

FROM arxiv/fulltext-api:0.3

RUN curl https://get.docker.com/ > getdocker.sh
RUN /bin/sh getdocker.sh

ADD bin/start_worker.sh /opt/arxiv/

VOLUME /pdfs

ENV WORKDIR /pdfs

ENTRYPOINT ["/opt/arxiv/start_worker.sh"]
CMD ["-A", "fulltext.worker.celery_app", "--loglevel=INFO", "-E", "--concurrency=2"]
