# arxiv/fulltext-worker

FROM arxiv/fulltext-api

RUN curl https://get.docker.com/ > getdocker.sh
RUN /bin/sh getdocker.sh

VOLUME /pdfs
VOLUME /data

ENV WORKDIR /pdfs

ENTRYPOINT ["pipenv", "run"]
CMD ["celery", "worker", "-A", "fulltext.worker.celery_app", "--loglevel=INFO", "-E", "--concurrency=2"]
