# arxiv/fulltext-agent

FROM arxiv/base:latest

# Add Python consumer and configuration.
ADD requirements/agent.txt /opt/arxiv/requirements.txt
RUN pip install -U pip && pip install -r /opt/arxiv/requirements.txt

ADD agent.properties /opt/arxiv/
ADD test.properties /opt/arxiv/
ADD bin/run_consumer.py /opt/arxiv/
ADD bin/start_agent.sh /opt/arxiv/
ADD bin/start_agent.py /opt/arxiv/


ENV PATH "/opt/arxiv:/opt/arxiv/jars:${PATH}"

# Runtime configuration.
ENV AWS_ACCESS_KEY_ID ""
ENV AWS_SECRET_ACCESS_KEY ""
# Set to `test` when testing with localstack.
ENV MODE "agent"

# Set `-Dcom.amazonaws.sdk.disableCertChecking` for testing
ENV JAVA_FLAGS ""

# Set `true` when testing with localstack.
ENV AWS_CBOR_DISABLE false

# If not set, secrets will not be retrieved.
ENV SECRETS_BUCKET_NAME ""
ENV ARXIV_HOME "https://arxiv.org"

RUN chmod +x /opt/arxiv/start_agent.sh

RUN ln -s /usr/bin/python3.6 /usr/local/bin/python3
RUN ln -s /usr/local/bin/python3 /usr/local/bin/python

# Add the application itself last, for faster builds on minor revisions.
ADD fulltext /opt/arxiv/fulltext/

CMD ["/bin/bash", "/opt/arxiv/start_agent.sh"]
