# arxiv/fulltext-api

FROM arxiv/base:latest

RUN pip install uwsgi

# Add Python consumer and configuration.
ADD requirements/web.txt /opt/arxiv/requirements.txt
ADD wsgi.py /opt/arxiv/
ADD bin/start_web.sh /opt/arxiv/
RUN pip install -U pip
RUN pip install -r /opt/arxiv/requirements.txt

ADD fulltext /opt/arxiv/fulltext/

ENV PATH "/opt/arxiv:${PATH}"

# Runtime configuration.
ENV AWS_ACCESS_KEY_ID ""
ENV AWS_SECRET_ACCESS_KEY ""

# If not set, secrets will not be retrieved.
ENV SECRETS_BUCKET_NAME ""
ENV ARXIV_HOME "https://arxiv.org"

EXPOSE 8000

WORKDIR /opt/arxiv/
CMD uwsgi --http-socket :8000 -w wsgi -t 3000 --processes 8 --threads 1 -M --async 100 --ugreen --manage-script-name
