# arxiv/fulltext-api

FROM arxiv/base:latest

WORKDIR /opt/arxiv

# Add Python consumer and configuration.
ADD Pipfile /opt/arxiv/
RUN pip install -U pip pipenv uwsgi
RUN pipenv install

ENV PATH "/opt/arxiv:${PATH}"

ENV LC_ALL en_US.utf8
ENV LANG en_US.utf8
ENV LOGLEVEL 40

ENV ARXIV_HOME "https://arxiv.org"

ADD fulltext /opt/arxiv/fulltext/
ADD wsgi.py /opt/arxiv/
ADD bin/start_api.sh /opt/arxiv/
EXPOSE 8000

WORKDIR /opt/arxiv/

ENTRYPOINT ["/opt/arxiv/start_api.sh"]
CMD ["--http-socket", ":8000", \
     "-M", \
     "-t 3000", \
     "--manage-script-name", \
     "--processes", "8", \
     "--threads", "1", \
     "--async", "100", \
     "--ugreen", \
     "--mount", "/fulltext=wsgi.py", \
     "--logformat", "%(addr) %(addr) - %(user_id)|%(session_id) [%(rtime)] [%(uagent)] \"%(method) %(uri) %(proto)\" %(status) %(size) %(micros) %(ttfb)"]
